apiVersion: v1
kind: Pod
metadata:
  name: busybox4
  labels:
    name: busybox
spec:
  hostname: busybox-4
  subdomain: default-subdomain
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 169.254.169.253
      - 10.100.0.10
    searches:
      - us-east-1.amazonaws.com
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0
