apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  labels:
    name: busybox
spec:
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
  dnsPolicy: Default  # policy applied to default
