apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: cbbox-clusterfirst
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: ClusterFirst
