apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 169.254.169.253
      - 10.100.0.10 
    searches:
      - idefault.svc.cluster.local 
      - svc.cluster.local 
      - cluster.local 
      - ec2.internal
    options:
      - name: ndots
        value: "2"
      - name: edns0

