
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: tutum/dnsutils 
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 169.254.169.253
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0
